version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.4

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install
      #- docker/setup-buildx-action:  # Set up Docker Buildx for building images
      #    version: "latest"
      #- docker/build:
          #path: .  # Build image using the Dockerfile in the root of the repo
  tag: ramdanse8/build-and-push:${12341234}  # Tag image with commit SHA
    - docker/login:
        username: $DOCKER_USERNAME  # Docker Hub username (set as environment variable in CircleCI)
        password: $DOCKER_PASSWORD  # Docker Hub password (set as environment variable in CircleCI)
    - docker/push:
        image: ramdanse8/build-and-push:${12341234}  # Push image to Docker Hub with commit SHA as tag
  test:
    docker: 
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test
  
workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires: 
            - build
      