version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@1.4.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Install dependencies"
          npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests"
          npm run test
  publish:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: DOCKER_LOGIN
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: ramdanse8/build-and-push
      - docker/push:
          image: ramdanse8/build-and-push
      - run: |
          echo "Publishing image to DockerHub"

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          context:
            - build-env-vars
            - docker-hub-creds
          requires:
            - build
            - test